### PR TITLE
Use PKOs template test framework

### PR DESCRIPTION
**Pull request by thetechnick**
### What type of PR is this?

_cleanup_

### What this PR does / Why we need it?

This PR uses Package Operators template test framework to make it easier to spot template problems without deploying the Package to an environment. The `.test-fixtures` directory is automatically generated from the packages templates and the test cases that can be defined in the PackageManifest.

To validate the package run this command in the project checkout:
`kubectl package validate ./package`

If you make changes to the source templates, either manually update the fixtures to match our expectations - or delete the `.test-fixtures` directory and the next `kubectl package validate` call will re-generate the directory, so you can inspect changes in git.

Documentation:
https://package-operator.run/docs/guides/packaging-an-application/#testing-templates

### Which Jira/Github issue(s) does this PR fix?

_Resolves #_

### Pre-checks (if applicable)

- [ ] Validated the changes in a hosted cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by bmeng** [comment]
@thetechnick Do we have a formal process to upgrade the PKO side changes to the dependent repos? 
Like this, when there is template change, we should be able to update the repo to match the latest version of PKO easily.

**Comment by thetechnick** [comment]
@bmeng Hey Bo Meng,
sorry for the late response.
I don't think we have a process to keep PKO tooling up-to-date across all repos.
In theory this should not matter enormously for these test fixtures, because they should never change just by updating PKO or the CLI.

**Comment by supreeth7** [comment]
A great way of testing our package templates, exactly what we were looking for.

/lgtm
/approve

**Pull request merged**
